### PR TITLE
Add SPDX SBOMs for all commits

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

This adds SPDX SBOMs for all commits.  This adds a new dependency of `syft` to the CI process, but not runtime.  It was selected after looking at a few options, including [ort](https://github.com/oss-review-toolkit/ort), [spdx-sbom-generator](https://github.com/sbom-generator/spdx-sbom-generator) and [tern]( https://github.com/tern-tools/tern).  Those tools did not fit my requirements, as they either didn't bundle stable binaries, didn't support running on macOS, or didn't support generating SBOMs from docker images.

Because I didn't have a great way to keep the version of `syft` up-to-date, the version installed in the CI pipeline isn't version pinned; it will install the latest `syft` release available on GitHub at runtime.  One of the mitigations of the build reproducibility gap that this causes is that the generated SBOM contains the version of the tool that generated it.

There is also a minor refactor in this PR to facilitate writing locally built docker images to disk, as it is needed both for SBOM generation and for trivy security scanning (both from aqua).  Neither of them directly support a feature (that I'm aware of) to not reach out to the remote docker registry and only look for images that are local.  I'm hoping to remove this as soon as possible and simply use the docker daemon (or similar) to facilitate finding the right version of the docker image.

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [X] Rebase your branch against the latest commit of the target branch
- [X] If you are adding a dependency, please explain how it was chosen
- [X] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [X] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by callmestu** [comment]
I updated the environment with `pipenv install --dev` but `pipenv run invoke sbom` fails looking for syft: `No such file or directory: 'syft'`
Should I install syft or should the normal method install it with pipenv take care of all the requirements @JonZeolla?

**Comment by JonZeolla** [comment]
Yup!  Syft needs to be installed, you can see how CI does it [here](https://github.com/SeisoLLC/easy_infra/pull/127/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR50) and that requirement is documented [here](https://github.com/SeisoLLC/easy_infra/pull/127/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R13).

**Comment by callmestu** [comment]
I spun my wheels for a bit trying to install syft in the following ways:
```
pip3 install syft
```
```
pipenv install syft
```
from PyPI but that is not the correct library/software! It led to dependency conflicts when installing and work-arounds still gave an error that syft wasn't available. Homebrew also didn't help - couldn't locate syft. 
I googled to find: https://github.com/anchore/syft 
which downloads and works properly. It might be helpful to disambiguate the syft dependency.

Otherwise, looks good. Approving.

**Review by callmestu — APPROVED** [review]
With the details about syft from the comments it's all very clear. Looks good. Approving.

**Comment by JonZeolla** [comment]
After this was merged the `Distribute` job began to fail due to https://github.com/anchore/syft/issues/696.  This wasn't an issue in my local because I was running `syft` 0.30.1, which doesn't have the bug.

**Pull request merged**
