### PR TITLE
Add commit hash to local builds

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

Add commit hash to local builds.  This reduces local build confusion between versioned docker images that have been released, and locally built docker images.

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [X] Rebase your branch against the latest commit of the target branch
- [X] If you are adding a dependency, please explain how it was chosen
- [X] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [X] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by callmestu** [comment]
After running `pipenv install --dev`  I still had to install gitpython.

**Comment by JonZeolla** [comment]
@callmestu 🤔 it is specified in the `Pipfile` and `Pipfile.lock`

**Review by callmestu — APPROVED** [review]
Hashes now included in the tags. Passes tests. approving.

**Comment by callmestu** [comment]
I would also like to know why I'm hitting this. Looking into it this morning, `pipenv shell` was activating an environment for another project/repo: IaC Scanning, where I was last working. After deleting easy_infra repo, cloning a new copy and running `pipenv install --dev`, things look good in `pipenv graph` where I can see both GitPython==3.1.24 and syft 0.6.0. 
Seems better, but not sure why that happened.

**Pull request merged**
