### PR TITLE
Add Terraform autodetect

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

This adds a Terraform autodetect capability for repos with multiple folders of unrelated (i.e. not modules) terraform.

- [x] Add tests

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [x] Rebase your branch against the latest commit of the target branch
- [x] If you are adding a dependency, please explain how it was chosen
- [x] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [x] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by JonZeolla** [comment]
The [recent check](https://github.com/SeisoLLC/easy_infra/runs/3757565768#step:7:60) failed as expected, whereas [previously](https://github.com/SeisoLLC/easy_infra/runs/3749968177#step:7:50) the same succeeded.

**Comment by callmestu** [comment]
I see this error in the log:
`2021-09-30T15:07:47.6357500Z [0m2021-09-30 15:07:47 [0;31m[ERROR][0m   Failed to get [GITHUB_TOKEN]!`
Should we look into that?

**Comment by JonZeolla** [comment]
That's optional, not an issue.  Only used when you want the goat to be able to comment on the pr itself.  Thanks for bringing it up though, good attention to detail 😁

**Review by callmestu — APPROVED** [review]
No other issues found. Approving.

**Pull request merged**
