### PR TITLE
Add centralized logging support

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

This adds support for logging to systems outside of the `easy_infra` runtime, using fluent-bit.  Still pretty space-efficient in my book:

```bash
CI=true dive seiso/easy_infra:latest-minimal | head -7 | grep 'efficiency' -A2
  efficiency: 99.3828 %
  wastedBytes: 6961052 bytes (7.0 MB)
  userWastedPercent: 1.2617 %
```

fluent-bit is a new dependency of the project, and it was chosen based off of its small footprint, and cloud-native capabilities, such as support for loki, prometheus, and Syslog outputs, as well as the more raw HTTP and tcp options.  It has a good architecture and a vibrant community (a part of the CNCF).

[Open Telemetry](https://opentelemetry.io/) was also considered, and would have actually been preferred except that the [status](https://opentelemetry.io/status/) of the logging spec is as follows.  In the future we should consider migrating from fluent-bit to open telemetry.
```bash
API: draft
SDK: draft
Protocol: experimental
Collector: experimental
```

## TODO
- [x] Add tests

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [X] Rebase your branch against the latest commit of the target branch
- [X] If you are adding a dependency, please explain how it was chosen
- [X] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [X] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by JonZeolla** [comment]
Auto-updates for `fluent-bit` don't work perfectly due to https://github.com/fluent/fluent-bit/issues/3987

**Comment by JonZeolla** [comment]
https://easy-infra.readthedocs.io/en/add-logging/Logging/index.html

**Review by seanctech — DISMISSED** [review]
Just need to fix dictionary for the CONTRIBUTING.md, otherwise looks good.

**Comment by JonZeolla** [comment]
@seanctech should be good to go now, can I get another quick look?

**Review by seanctech — APPROVED** [review]
LGTM

**Pull request merged**
