### PR TITLE
Add hashicorp vault helpers

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments
Add the hashicorp vault helper tools, `envconsul` and `consul-template`.  They also apply to consul, hence the names, but that is not the purpose of them being included here.

## TODO
- [x] Fix update mechanism.  Pending:
  - [x] hashicorp/envconsul#251
  - [x] hashicorp/consul-template#1437

## Pull Request Checklist
Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:
 - [X] Ensure that `make build` completes successfully
 - [X] Rebase your branch against the latest commit of the target branch, which likely should be `master`
 - [X] If there is an issue associated with your Pull Request, align your PR title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by JonZeolla** [comment]
Rebased on `master`, still blocked externally

**Comment by JonZeolla** [comment]
Kick CI

**Comment by JonZeolla** [comment]
Asked for updates on the blockers; need to update this branch after #60

**Comment by JonZeolla** [comment]
Rebased on `main`

**Comment by JonZeolla** [comment]
Ready for review!

**Review by callmestu — APPROVED** [review]
Builds locally. Files are in the container where they're supposed to be. Approving.

**Pull request merged**
