### PR TITLE
Update primary components

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

Update primary components

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [X] Rebase your branch against the latest commit of the target branch
- [X] If you are adding a dependency, please explain how it was chosen
- [X] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [X] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by callmestu** [comment]
Built locally. Used ~200% CPU running `terraform validate` for ~45 mins then CPU dropped to low teens. Still has not completed `terraform validate` 2.5 hours later @JonZeolla

**Comment by JonZeolla** [comment]
@callmestu very interesting.  I am not seeing that in my environment, and nor is CI.  🤔 

Which tag are you running in?

**Comment by callmestu** [comment]
`docker run -it -v /Users/christomei/src/seiso/easy_infra:/iac seiso/easy_infra` pulled from `ps`
`docker run -it -v $(pwd):/iac seiso/easy_infra` actual CLI text.
I usually use latest but removed it this time and left the container untagged. 
At least yesterday CI and my local were doing the same thing.

**Comment by callmestu** [comment]
I think my fix here is to not run from the root of the easy_infra folder itself. Everything else works.

**Review by callmestu — APPROVED** [review]
Looks good. Tests pass. Approving.

**Pull request merged**
