### PR TITLE
ci: Improve logging and make the clean task more thorough

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

Additional sbom improvements due to the transient issues we ran into with b4e44dc08cf88ec0b74734a005786c63240518c0 due to https://github.com/anchore/syft/issues/696

This adds logging and will cleanup generated SBOMs if you run `pipenv run invoke clean`

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [X] Rebase your branch against the latest commit of the target branch
- [X] If you are adding a dependency, please explain how it was chosen
- [X] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [X] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by callmestu** [comment]
`terraform validate` within `easy_infra:latest` is taking more than 1 hour to complete. With PR128 (built and tested earlier today) this only took a few minutes.

**Comment by callmestu** [comment]
`terraform validate` succeeded after 74 minutes. 
I actually forgot to checkout the branch I made for this PR - I noticed that `pipenv run invoke clean` didn't remove the sbom files. Building/testing the right branch now.

**Comment by callmestu** [comment]
Built in 11+ minutes. Debug logs look good. Running `terraform validate` now.

**Comment by JonZeolla** [comment]
@callmestu very interesting; CI finished in just under an hour and it runs many `terraform validate`s.  Is your system under load?

**Comment by JonZeolla** [comment]
Can you see if https://github.com/SeisoLLC/easy_infra/pull/130 helps?

**Comment by callmestu** [comment]
Docker only appears to be using <10% CPU for the last few hours. I just cancelled `terraform validate` in interactive docker of easy_infra:latest
```easy_infra@f7440721ffb4:/iac$ terraform validate
INFORMATIONAL:  Passed terraform init -backend=false initialization
INFORMATIONAL:  Passed terraform validate validation
^CERROR:  Failed checkov directory scan
```
So it appears to have been in checkov, @JonZeolla.

**Comment by JonZeolla** [comment]
@callmestu very interesting. I am not seeing that in my environment, and nor is CI. 🤔

Which tag are you running in, and from what directory? Can you provide your docker run command?  I just ran the following and the `terraform` command completed in 32 seconds.

```bash
pipenv run invoke build
cd tests/terraform/checkov
docker run -it -v $(pwd):/iac seiso/easy_infra:latest-minimal terraform validate
```

**Comment by callmestu** [comment]
> ```shell
> cd tests/terraform/checkov
> docker run -it -v $(pwd):/iac seiso/easy_infra:latest-minimal terraform validate
> ```
completes for me in 10s. Looks like I can run the full image on that folder as well.  Maybe I should not run the docker image from the root of easy_infra.

**Review by callmestu — APPROVED** [review]
Clean functionality works. Other tests pass. Approving.

**Pull request merged**
