### PR TITLE
Add opentofu support

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

This adds OpenTofu support

## Pull Request Checklist

Thank you for submitting a contribution to our project!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [x] Rebase your branch against the latest commit of the target branch.
- [x] If you are adding a dependency, please explain how it was chosen.
- [x] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results.
- [x] If there is an issue associated with your Pull Request, link the issue to the PR.
- [x] Validate that documentation is accurate and aligned to any project updates or additions.

Don't forget our more detailed contribution guidelines
[here](https://github.com/SeisoLLC/operations/blob/main/documents/software-guidelines.md#contributing-to-a-repository).

### CODE REVIEW

**Comment by JonZeolla** [comment]
WIP; will be blocked on https://github.com/tfutils/tfenv/pull/411 merge in the future once the kinks are ironed out

**Comment by JonZeolla** [comment]
We hit some `ansible` issues during this PR because of https://github.com/Checkmarx/kics/issues/6753

**Comment by JonZeolla** [comment]
This is ready for tests to be added

**Review by ChiefHolland — APPROVED** [review]
Looks good!

**Comment by kvendingoldo** [comment]
Hello there,
[Tofuenv's](https://github.com/tofuutils/tofuenv) first stable release (v1.0) is now available! tofuenv is a fork of tfenv that only works with OpenTofu binaries. Our crew (me, @anastasiiakozlova245, @Nmishin) has been working on the fork over the past week. We worked hard to improve the usability of core [tofuenv](https://github.com/tofuutils/tofuenv) features, add some new capabilities, and, of course, fix a few bugs in the original [tfenv](https://github.com/tfutils/tfenv) program.

We'd appreciate your input and support on GitHub. Please feel free to submit issues and make contributions. Link to tofuenv: https://github.com/tofuutils/tofuenv

tofuenv can be installed manually from GitHub or via brew (for mac users).

**Pull request merged**
