### PR TITLE
Add daily auto updater github action

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments

Add daily auto updater github action

## Pull Request Checklist

Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:

- [x] Rebase your branch against the latest commit of the target branch
- [x] If you are adding a dependency, please explain how it was chosen
- [x] If manual testing is needed in order to validate the changes, provide a testing plan and the expected results
- [x] If there is an issue associated with your Pull Request, align your PR
  title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by callmestu** [comment]
This passes CI and my local test. I'm curious how the update.yml workflow itself is tested.

**Comment by JonZeolla** [comment]
@callmestu we could run it on another branch or in another project but there's no perfect way to test.  🤞

**Comment by callmestu** [comment]
OK, that's what I thought from my previous gh action task. Thanks.

**Review by callmestu — APPROVED** [review]
Passes CI and local. LGTM. Approved.

**Pull request merged**
