### PR TITLE
Speed up the interactive docker initialization

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments
This is a PR to speed up the interactive docker initialization.

This was initially a PR to add `gitleaks` to run at the `easy_infra` interactive entrypoint but that decision was abandoned.

## Pull Request Checklist
Thank you for submitting a contribution to `easy_infra`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:
 - [X] Rebase your branch against the latest commit of the target branch, which likely should be `main`
 - [X] If there is an issue associated with your Pull Request, align your PR title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by JonZeolla** [comment]
Rebased on `main`

**Review by jimmio — COMMENTED** [review]
When I run `docker build -t easy_infra_pr_62 .`, the build fails because `${ANSIBLE_VERSION}` is empty:
```
...
Step 19/51 : RUN apt-get update  && apt-get -y install --no-install-recommends ansible=${ANSIBLE_VERSION}
...
Fetched 17.0 MB in 3s (6130 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '' for 'ansible' was not found
```

**Comment by JonZeolla** [comment]
You need to `pipenv install --dev && pipenv run invoke build`

**Review by jimmio — APPROVED** [review]
Got it working -- Init is definitely faster

**Pull request merged**
